export class EnrollReport{
    schoolyearfrom:number;
    schoolyearto:number;
    type:any;
    department:any;
    grade:any;
    course:any;
    strand:any;
    semester:any;
    gender:any;
    status:any;
    Subject:any;
    IsCheckedReportSchool:boolean;
    IsCheckedReportDept:boolean;
    IsCheckedReportGender:boolean;
    IsCheckedReportGrade:boolean;
    IsCheckedReportCourse:boolean;
    IsCheckedReportStrand:boolean;
    IsCheckedReportSem:boolean;
}